# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel:
      - sustaining-notify
      - chef-notify

# This publish is triggered by the `built_in:publish_rubygems` artifact_action.
rubygems:
  - win32-mmap

release_branch:
  - ffi

subscriptions:
  # These actions are taken, in order they are specified, anytime a Pull Request is merged.
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Exclude From Changelog"
            - "Expeditor: Skip All"
      - built_in:build_gem:
          only_if: built_in:bump_version

  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:rollover_changelog
      - built_in:publish_rubygems